// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDudy6EdHC4CZylD0rS7TcMvhKv6fxEVyw',
    appId: '1:375522224086:web:86f405d1459dad2f3ce677',
    messagingSenderId: '375522224086',
    projectId: 'gatemate-93f52',
    authDomain: 'gatemate-93f52.firebaseapp.com',
    storageBucket: 'gatemate-93f52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOizunTF-nLZdpq-90ypg8GCcdnZ9HcI',
    appId: '1:375522224086:android:24cc9e4490e455f13ce677',
    messagingSenderId: '375522224086',
    projectId: 'gatemate-93f52',
    storageBucket: 'gatemate-93f52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaspTycdNsxJxHSXxF56hYhak-P_pkl74',
    appId: '1:375522224086:ios:a9d2cca4fe1e39c23ce677',
    messagingSenderId: '375522224086',
    projectId: 'gatemate-93f52',
    storageBucket: 'gatemate-93f52.appspot.com',
    iosClientId: '375522224086-vqf8ntm7qn4ujck10m9sgkubv1m61t6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatemateMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaspTycdNsxJxHSXxF56hYhak-P_pkl74',
    appId: '1:375522224086:ios:a9d2cca4fe1e39c23ce677',
    messagingSenderId: '375522224086',
    projectId: 'gatemate-93f52',
    storageBucket: 'gatemate-93f52.appspot.com',
    iosClientId: '375522224086-vqf8ntm7qn4ujck10m9sgkubv1m61t6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatemateMobile',
  );
}
